version: 2.1

jobs:
  build-docker-image:
    docker:
      # replace with your preferred image
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: 
            docker build -t .

workflows:
  example-workflow:
    jobs:
      - build-docker-image