version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-docker-image:
    docker:
      # replace with your preferred image
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/build:
          image: hoangnhdocker/circleci 
          use-buildkit: true 
          treat-warnings-as-errors: false
      - docker/push:
          image: hoangnhdocker/circleci

workflows:
  example-workflow:
    jobs:
      - build-docker-image