version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - docker/check
      - docker/build:
          image: hoangnhdocker/circleci
      - docker/push:         
          image: hoangnhdocker/circleci
workflows:
  commit:
    jobs:
      - build-and-push
