version: 2.1
orbs:
  docker: circleci/docker@2.2.0

workflows:
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          image: hoangnhdocker/circlrci
          remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true
          use-remote-docker: true
