version: 2.1

jobs:
  build-docker-image:
    docker:
      # replace with your preferred image
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: 
            docker build -t hoangnhdocker/circleci:latest .
      - run:
          name: Push image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push hoangnhdocker/circleci:latest

workflows:
  example-workflow:
    jobs:
      - build-docker-image